Te tabbed interface
Testell/photogram-industrial pull request #5
Opened 2024-10-17 16:43 UTC by Testell

2024-10-17 18:04 UTC, armstrca commented on app/views/users/_profile_nav.html.erb
> +  <div class="col md-6">
`col-md-6 offset-md-3` instead of `col md-6`

2024-10-17 18:23 UTC, armstrca requested changes
Fix the CSS I mentioned but otherwise looks good

2024-10-17 19:20 UTC, jessjno approved these changes
looks good!

2024-10-17 20:10 UTC, armstrca approved these changes

2024-10-17 20:52 UTC, merged

2024-10-18 21:06 UTC, dsimp reviewed
Nice format